name: ussd_service
description: "Send USSD requests and get the response (Android API 26+). V2 embedding."
version: 0.0.1
homepage: "none"

environment:
  sdk: '>=3.0.0 < 4.0.0'
  flutter: '>=3.19.0'

flutter:
  plugin:
    platforms:    
      android: 
        package: com.wbrandt.ussd_service
        pluginClass: UssdServicePlugin    

dependencies:
  flutter:
    sdk: flutter  